### ISSUE TITLE
Graceful shutdown ?

### ISSUE THREAD

**Issue by suhasghorp** [absperf/asyncinotify#4]
Hello, I like this library and I am planning to put it to some real use. One question I have, is there anyway to shutdown the event loop gracefully? My use case is, the process to look for file modifications will run all day in a scheduler and in the evening, I need to bring it down by scheduling another process. Obviously, there will be no user interaction to do Ctrl+C to shut it down.

Another question - I am only interested in file modification events, I will be monitoring a log file. Is there anyway to pick up the 
string/line that was appended to the file which triggered the event? If there is no built-in way to do that, what would be correct way to get that change ?

Thank you.

**Comment by Taywee** [comment]
> One question I have, is there anyway to shutdown the event loop gracefully.

Depends what you mean.  If you mean actually shutdown the asyncio event loop, you can always access the event loop and shut it down directly (with something like `get_running_loop().stop()`), but that's usually bad form with modern asyncio code.

Running it in a task and cancelling the task is probably the best way.  There were some bugs around cancellation in the past, but most of those should be addressed now.  For example:

```python
from asyncio import run, create_task, sleep
from asyncinotify import Inotify, Mask

async def watch():
    with Inotify() as inotify:
        inotify.add_watch('.', Mask.ATTRIB)
        async for event in inotify:
            print(event)

async def main():
    task = create_task(watch())
    await sleep(2)
    task.cancel()

run(main())
```

That watches for 2 seconds and then cancels the inotify task.  Just make sure that you don't swallow any `CancelledError` in the task.

> Is there anyway to pick up the string/line that was appended to the file which triggered the event?

Not one that's free of race conditions, but there are two obvious ways:

* You can stat the file for its size, and compare the differences between the sizes.  Keeping the last few sizes will let you open the file, seek to the first size, and read the difference in bytes to get the lines.
* Keep an open filehandle and read it every time you get a `MODIFY` event.  You will also occasionally have to stat the path to make sure the inode hasn't changed (log file rotation) and to make sure the file size hasn't dropped to `0` with the same inode (file truncation).  Note that if you're just watching the file itself, rotation will mess things up, because you'll be still watching the previous path, not the new one.  You'll also have to watch the directory to be able to tell when the file is renamed or deleted.

**Comment by Taywee** [comment]
I've closed this ticket, but feel free to ask more here if you're not clear on anything, or ping in the [Python matrix room](https://matrix.to/#/#python:matrix.org).
